// <auto-generated />
namespace final_BS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class finalBS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalBS));
        
        string IMigrationMetadata.Id
        {
            get { return "202012191455045_final-BS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
